/*
 *
 * HomePage constants
 *
 */

export const FETCH_JOINED_COUNTS = 'FETCH_JOINED_COUNTS';
export const FETCH_JOINED_COUNTS_SUCCESS = 'FETCH_JOINED_COUNTS_SUCCESS';
export const FETCH_JOINED_COUNTS_ERROR = 'FETCH_JOINED_COUNTS_ERROR';

export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR';
